spring.application.name=backend

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/moim_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=moim_user
spring.datasource.password=mom_1234_5678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379